baseUrl : "https://YNH_APP_DOMAIN/YNH_WWW_PATH"
databaseConfiguration :
    host : "localhost"
    database : "YNH_WWW_APP"
    username : "YNH_WWW_APP"
    password : "YNH_DB_PASS"
adminUser : 
    username : "YNH_ADMIN_USER"
    password : "YNH_ADMIN_PASS"
    password_confirmation : "YNH_ADMIN_PASS"
    email : "YNH_ADMIN_EMAIL"
settings : 
    forum_title : "YNH_FORUM_TITLE"
