baseUrl : "https://__DOMAIN____PATH__"
databaseConfiguration :
    host : "localhost"
    database : "__DB_NAME__"
    username : "__DB_NAME__"
    password : "__DB_PWD__"
adminUser :
    username : "__ADMIN__"
    password : "__PASSWORD__"
    password_confirmation : "__PASSWORD__"
    email : "__EMAIL__"
settings :
    forum_title : "__TITLE__"
