baseUrl : "https://__DOMAIN____PATH__"
databaseConfiguration :
    host : "localhost"
    database : "__USER__"
    username : "__USER__"
    password : "__DB_PWD__"
adminUser :
    username : "__ADMIN__"
    password : "__ADMIN_PWD__"
    password_confirmation : "__ADMIN_PWD__"
    email : "__ADMIN_MAIL__"
settings :
    forum_title : "__TITLE__"
